CREATE TABLE funcionario (
    id BINARY(16) NOT NULL PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(15) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    cargo ENUM('OPERACIONAL', 'ADMINISTRATIVO', 'TEMPORARIO') NOT NULL,
    status ENUM('ATIVO', 'SUSPENSO', 'REMOVIDO') NOT NULL,
    foto_url VARCHAR(255),
    ultimo_login TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pateo_id BINARY(16) NOT NULL,
    CONSTRAINT fk_funcionario_pateo FOREIGN KEY (pateo_id) REFERENCES pateo(id)
);